name: monolith
description: "Monolith — local music player. Material 3, OLED dark, waveform-as-navigation."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.2
  provider: ^6.1.2
  flutter_soloud: ^4.0.3
  youtube_explode_dart: ^3.0.5
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
